[api]
key = "eqGx6cCkcr72oQFgYOl6F6kmgbeRFfF69HvcZ5mk"
userkey = "Cs11d6uGFPDQg1NFSanUZuAmWDFiyTDCGtTljnpFL217IlRlbmFudCI6ICI2OTEwMDAwNyIsICJFbWFpbCI6ICJoLnNhdG9taUBrZW5kd2ViLm5ldCIsICJJZCI6ICIyNWY3OWNiYi01ZGFhLTQ2NjItYmRlYi02N2JjYjFiNDhiMDUiLCAiTmVvVXNlciI6ICJhZG1pbiIsICJJc3N1ZWRBdCI6ICIyMDI0LTExLTE0VDA1OjIwOjQ0WiIsICJFeHBpcmF0aW9uIjogIjIwMzQtMTEtMTJUMDU6MjA6NDNaIn0="
db = "KdwGnkDat01"
